name: Publish version

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm ci
      - run: git log -n 2 --pretty=format:%H -- CHANGELOG.md | tail -n +2
      - run: |
          commit="$(git log -n 2 --pretty=format:%H -- CHANGELOG.md | tail -n +2)"
          echo "CHANGES=git diff $commit HEAD -- CHANGELOG.md | sed -n '/^diff/,/^diff/p' | grep '+' | tail -n +6 | awk '{print substr($0, 2)}'" >> $GITHUB_OUTPUT
        id: changes

      - uses: softprops/action-gh-release@v2
        with:
          body: ${{steps.changes.outputs.CHANGES}}
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}