concurrency:
  group: ${{ github.workflow }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_CUSTOM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: JoshuaKGoldberg/release-it-action@v0.2.2

name: Release

on:
  push:
    branches:
      - release

permissions:
  contents: write
  id-token: write